config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  get 'login' => 'sessions#new', as: 'login'
  get 'signup' => 'users#new', as: 'signup'
  get 'logout' => 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :events
  resources :attendances, only: [:new, :create, :destroy, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user, class_name: 'User'
  validates :name, presence: true, length: { minimum: 5 }
  validates :description, presence: true, length: { minimum: 5 }
  validates :date, :location, presence: true
  has_many :attendances
  has_many :attendees, through: :attendances, source: :user
  scope :past, -> { where('date < ?', Date.today) }
  scope :upcoming, -> { where('date >= ?', Date.today) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, length: { minimum: 4 }
  has_many :events
  has_many :attendances
  has_many :attended_events, through: :attendances, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper

  private

  def require_login
    redirect_to login_path, alert: 'Sign up or Log in to see the events!' unless current_user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/attendance_controller.rb
class AttendanceController < ApplicationController
  before_action :require_login

  def create
    event = Event.find(params[:event_id])
    attendance = Attendance.new(event_id: event.id, user_id: params[:user_id])

    if attendance.save
      attendance.invited!
      flash[:notice] = 'Invitation sent!'
      redirect_to users_path(event_id: event.id)
    else
      flash[:alert] = 'Invitation could not be sent'
      redirect_to event_path(event)
    end
  end

  def destroy
    event = Event.find(params[:event_id])
    attendance = Attendance.find(params[:id])
    if current_user == event.user
      attendance.destroy
      flash[:notice] = 'Invitation cancelled!'
    else
      attendance.invited!
      flash[:notice] = "You're not longer assisting #{event.name}!"
    end

    redirect_to users_path(event_id: event.id, id: enrollment.id)
  end

  def update
    @event = Event.find(params[:event_id])
    @attendance = Attendance.find_by(event_id: params[:event_id], user_id: current_user.id)
    if @attendance&.invited?
      @attendance.accepted!
      flash[:notice] = "Thank you for signing up for the '#{@event.name}'!"
    else
      flash[:alert] = 'Your name is not on the invitation list'
    end

    redirect_to event_path(@event)
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  include AttendancesHelper
  before_action :require_login

  def create
    event = Event.find(params[:event_id])
    attendance = Attendance.new(event_id: event.id, user_id: params[:user_id])

    if attendance.save
      flash[:notice] = 'Invitation sent!'
      redirect_to users_path(event_id: event.id)
    else
      flash[:alert] = 'Invitation could not be sent'
      redirect_to event_path(event)
    end
  end

  def destroy
    event = Event.find(params[:event_id])
    attendance = Attendance.find(params[:id])
    if current_user == event.user
      attendance.destroy
      flash[:notice] = 'Invitation cancelled!'
    else
      flash[:notice] = "You're not longer assisting #{event.name}!"
    end

    redirect_to users_path(event_id: event.id, id: attendance.id)
  end

  def update
    @event = Event.find(params[:event_id])
    @attendance = Attendance.find_by(event_id: params[:event_id], user_id: current_user.id)
    if @attendance
      flash[:notice] = "Thank you for signing up for the '#{@event.name}'!"
    else
      flash[:alert] = 'Your name is not on the invitation list'
    end

    redirect_to event_path(@event)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper
  before_action :require_login, except: [:index]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
    @event = Event.find(params[:id])
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events or /events.json
  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to action: 'show', id: @event.id
    else
      render :new
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:name, :date, :location, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by_username(params[:username])
    if user
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in!'
    else
      flash.now.alert = 'Name is invalid'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash.notice = "User #{@user.username} successfully created!"
      redirect_to user_path(@user)
    else
      flash.notice = 'Invalid username'
      render 'new'
    end
  end

  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def createv
    link_to 'Create event', new_event_path, class: 'button is-white'
  end

  def logoutme
    link_to 'Logout', logout_path, class: 'button is-white'
  end

  def signinme
    link_to 'Sign In', login_path, class: 'button is-white'
  end

  def signupme
    link_to 'Sign Up', signup_path, class: 'button is-white'
  end

  def linktocurr
    link_to current_user.username, user_path(current_user), class: 'button is-white'
  end

  def linktoroot
    link_to 'Private Events', root_path, class: 'navbar-item'
  end

  def flasha
    flash[:alert]
  end

  def flashnot
    flash[:notice]
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  def attfindb
    Attendance.find_by(event_id: @event.id, user_id: current_user.id)
  end

  def userrej
    @users.reject { |user| user == Event.find(params[:event_id]).user }
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def link_toattend
    link_to 'Attend', root_path, class: 'button is-primary is-large is-fullwidth', notice: 'Thank you'
  end

  def link_toevent
    link_to 'Back to Event', root_path, class: 'button is-fullwidth'
  end

  def linkto_event(event)
    link_to event.name, event_path(event), class: 'card-header-title is-centered'
  end

  def link_back
    link_to 'Back to Event', event_path(id: params[:event_id]), class: 'button is-fullwidth'
  end

  def event_trunc(event)
    event.description.truncate_words(18)
  end

  def upcomingev
    @user.attended_events.where('date >= ?', Date.today)
  end

  def attevents
    @user.attended_events.where('date < ?', Date.today)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def userfinmap
    User.find(@event.attendances.map(&:user_id))
  end
end

app/views/attendances/create.html.erb
<h1>Attendances#create</h1>
<p>Find me in app/views/attendances/create.html.erb</p>

app/views/attendances/destroy.html.erb
<h1>Attendaces#destroy</h1>
<p>Find me in app/views/attendances/destroy.html.erb</p>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |f| %>
  <div class="field">
    <div class="control">
      <%= f.label :name, class: "label" %>
      <%= f.text_field :name, class: "input", autofocus: true %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.label :date, class: "label" %>
      <%= f.date_select :date, type: "date", class: "input" %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.label :location, class: "label" %>
      <%= f.text_field :location, class: "input" %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.label :description, class: "label" %>
      <%= f.text_field :description, class: "textarea" %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.submit "Create Event", class:"button is-primary is-large is-fullwidth" %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= link_to 'Cancel', root_path, class:"button is-large is-fullwidth" %>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="top">
  <div class="section">
    <h2 class="title is-2">Upcoming Events</h2>
    <div class="columns">
      <% @events.upcoming.each do |event| %>
        <div class="column is-3">
          <div class="card">
            <header class="card-header">
              <%= linkto_event(event) %>
            </header>
            <div class="card-content">
              <div class="content has-text-justified">
                <%= event_trunc(event) %>
              </div>
            </div>
            <footer class="card-footer">
              <p class="card-footer-item is-narrow"><%= event.date %></p>
              <p class="card-footer-item"><%= event.location %></p>
            </footer>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="bottom">
  <div class="section">
    <h2 class="title is-2">Past Events</h2>
    <div class="columns">
      <% @events.past.each do |event| %>
        <div class="column is-3">
          <div class="card">
            <header class="card-header">
              <%= linkto_event(event) %>
            </header>
            <div class="card-content">
              <div class="content has-text-justified">
                <%= event_trunc(event) %>
              </div>
            </div>
            <footer class="card-footer">
              <p class="card-footer-item"><%= event.date %></p>
              <p class="card-footer-item"><%= event.location %></p>
            </footer>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <div class="box">
          <h2 class="title is-2 is-spaced has-text-centered mb-6"><%= @event.name %></h2>

          <div class="columns is-mobile is-centered">
            <div class="column is-5">
              <p><small>Hosted by</small></p>
              <h4 class="subtitle is-4"><%= @event.user.username %></h4>
            </div>
            
            <div class="column">
              <div class="dropdown is-hoverable">
                <div class="dropdown-trigger">
                    <button class="button is-fullwidth" aria-haspopup="true" aria-controls="dropdown-menu3">
                      <span>Invitees: <%= userfinmap.count %></span>
                    </button>
                  </div>
                <div class="dropdown-menu" id="dropdown-menu6" role="menu">
                  <div class="dropdown-content">
                    <ul>
                      <% if userfinmap.any? %>
                        <div class="dropdown-item">
                          <% userfinmap.each do |user| %>
                            <li><p><%= user.username %></p></li>
                          <% end %>
                        </div>
                      <% end %>
                    </ul>
                  </div>
                </div>
              </div>
            </div>

            <div class="column">
              <div class="dropdown is-hoverable">
                <div class="dropdown-trigger">
                  <button class="button is-fullwidth" aria-haspopup="true" aria-controls="dropdown-menu3">
                    <span>Attendies: <%= userfinmap.count %></span>
                  </button>
                </div>
                <div class="dropdown-menu" id="dropdown-menu6" role="menu">
                  <div class="dropdown-content">
                    <ul>
                      <% if userfinmap.any? %>
                        <div class="dropdown-item">
                          <% userfinmap.each do |user| %>
                            <li><p><%= user.username %></p></li>
                          <% end %>
                        </div>
                      <% end %>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <p class="has-text-justified"><%= @event.description %></p><br/>

          <div class="columns is-mobile is-centered">
            <div class="column">
              <div class="card">
                <div class="card-header">
                  <p class="card-header-title is-centered"><%= @event.location %></p>
                </div>
              </div>
            </div>
            <div class="column">
              <div class="card">
                <div class="card-header">
                  <p class="card-header-title is-centered"><%= @event.date %></p>
                </div>
              </div>
            </div>
          </div>

          <br/>

          <% if @event.user == current_user %>
            <%= button_to "Invite", users_path, params: {:event_id => @event.id}, method: :get, class: "button is-info is-large is-fullwidth" %>
          <% else %>
            <% attfindb %>
            <% if attfindb  %>
              <%= button_to "Cancel attendance", attendance_path(id: attendance.id, event_id: @event.id, user_id: current_user.id), method: :delete, class: "button is-danger is-large is-fullwidth" %>
            <% else %>
              <%= link_toattend %>
            <% end %>
          <% end %>

          <br/>

          <%= link_toevent %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if flashnot %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flasha %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= linktoroot do %>
          <h1 class="title is-4">Events</h1>
        <% end %>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarExample" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
              <p class="control">
                <% if current_user != nil %>
                <%= createv %>
                <% end %>
              </p>
              <% if current_user %>
                <p class="control">
                  <%= linktocurr %>
                </p>
                <p>
                  <%= logoutme %>
                </p>
              <% else %>
                <p class="control">
                  <%= signinme %>
                </p>
						    <p class="control">
                  <%= signupme %>
                </p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <div class="field">
    <div class="control">
      <%= f.label :username, class: "label" %>
      <%= f.text_field :username, class: "input", autofocus: true %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.submit "Sign Up", class: "button is-primary is-large is-fullwidth" %>
    </div>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <div class="box">
          <h2 class="title is-2 is-spaced has-text-centered mb-6">Guest List</h2>
    
          <div class="columns is-centered">
            <table class="table is-fullwidth is-hoverable">
              <tbody>
                <th class="has-text-centered">Name</th>
                <th class="has-text-centered">Status</th>
                <th class="has-text-centered">Action</th>
                <% userrej.each do |user| %>
                  <% attendance = Attendance.find_by(event_id: params[:event_id], user_id: user.id) %>
                  <tr>
                    <td class="has-text-centered">
                      <%= user.username %>
                    </td>
                    <% unless attendance.nil? || attendance.status.nil? %>
                      <td class="has-text-centered">
                        <span class="tag is-primary is-medium is-light"><%= attendance.status %><span>
                      </td>
                    <% else %>
                      <td></td>
                    <% end %>
                    <% if attendance.nil? %>
                      <td class="has-text-centered">
                        <%= button_to "Invite", attendances_path(event_id: params[:event_id], user_id: user.id), class: "button is-primary is-small" %>
                      </td>
                    <% else %>
                      <td class="has-text-centered">
                        <%= button_to "Cancel Invitation", attendance_path(id: attendance.id, event_id: params[:event_id]), method: :delete, class: "button is-danger is-small" %>
                      </td>
                    <% end %>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>

          <br/>

          <%= link_back %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="section">
  <div class="container">
	<div class="columns is-centered">
      <div class="column is-4">
        <h2 class="title is-2 is-spaced has-text-centered">Sign Up</h2>
        <%= render 'form', user: @user %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="section">
  <div class="container">
	  <div class="columns is-centered">
      <div class="column is-9">
        <h2 class="title is-2 is-spaced has-text-centered"><%= @user.username %>'s Profile</h2>
	      <div class="columns is-centered">
          <div class="column has-text-centered">
            <h3 class="subtitle is-3 has-text-centered">Hosted Events: <%= @user.events.count %></h3>
            <ul>
              <% if @user.events.empty? %>
                <p>User is not hosting</p>
              <% else %>
                <% @user.events.each do |event| %>
                  <li class="has-text-centered"><%= link_toevent %></li>
                <% end %>
              <% end %>
            </ul>
          </div>

          <div class="column has-text-centered">
            <h3 class="subtitle is-3">Upcoming Events: <%= upcomingev.count %></h3>
            <ul>
              <% if upcomingev.count.zero? %>
                <p>No planned parties</p>
              <% else %>
                <% upcomingev.each do |event| %>
                  <li class="has-text-centered"><%= link_toevent %></li>
                <% end %>
              <% end %>
            </ul>
          </div>

          <div class="column has-text-centered">
            <h3 class="subtitle is-3 has-text-centered">Attended Events: <%= attevents.count %></h3>
            <ul>
              <% if @user.attended_events.empty? %>
                <p>User is not partying</p>
              <% else %>
                <% attevents.each do |event| %>
                  <li class="has-text-centered"><%= link_toevent %></li>
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>